#!/usr/bin/env python3
"""
Generate Python Project Structure Tool

Generates Python project structure based on development standards,
including pyproject.toml, source layout, and tooling configuration.

Usage:
    python3 generate_python_project.py <system_root> --service <service_name> [options]

Options:
    --service <name>        Service/project name to generate
    --standards <path>      Path to development_standards.json (default: auto-detect)
    --output-dir <path>     Output directory (default: services/<service_name>)
    --dry-run               Show what would be generated without creating files
    --force                 Overwrite existing files

Examples:
    # Generate service with auto-detected standards
    python3 generate_python_project.py /path/to/system --service user_service

    # Generate with explicit standards file
    python3 generate_python_project.py /path/to/system --service api_gateway \\
        --standards specs/development/development_standards.json

Created: 2025-11-23
Version: 1.0.0
Reflow Version: 3.20.0
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


def load_development_standards(system_root: str) -> Optional[dict[str, Any]]:
    """Load development standards from system."""
    standards_path = Path(system_root) / "specs" / "development" / "development_standards.json"
    if standards_path.exists():
        with open(standards_path) as f:
            return json.load(f)
    return None


def get_python_standards(standards: dict[str, Any]) -> dict[str, Any]:
    """Extract Python standards from development standards."""
    return standards.get("language_standards", {}).get("python", {})


def generate_pyproject_toml_hatchling(
    service_name: str,
    python_standards: dict[str, Any],
    description: str = "Generated by Reflow"
) -> str:
    """Generate pyproject.toml for hatchling build system."""

    # Get settings from standards
    web_framework = python_standards.get("web_framework", {}).get("value", "fastapi")
    orm = python_standards.get("orm", {}).get("value", "sqlalchemy")
    testing = python_standards.get("testing_framework", {}).get("value", "pytest")
    linting = python_standards.get("linting", {}).get("value", "ruff")
    type_checking = python_standards.get("type_checking", {}).get("value", "mypy")
    logging = python_standards.get("logging", {}).get("value", "structlog")
    http_client = python_standards.get("http_client", {}).get("value", "httpx")
    configuration = python_standards.get("configuration", {}).get("value", "pydantic_settings")

    # Build dependencies list
    dependencies = []

    # Web framework
    if web_framework == "fastapi":
        dependencies.extend([
            '"fastapi>=0.109.0"',
            '"uvicorn[standard]>=0.27.0"',
        ])
    elif web_framework == "flask":
        dependencies.append('"flask>=3.0.0"')
    elif web_framework == "django":
        dependencies.append('"django>=5.0"')
    elif web_framework == "litestar":
        dependencies.append('"litestar>=2.0.0"')

    # ORM
    if orm == "sqlalchemy":
        dependencies.append('"sqlalchemy>=2.0.0"')
    elif orm == "sqlmodel":
        dependencies.append('"sqlmodel>=0.0.14"')
    elif orm == "tortoise":
        dependencies.append('"tortoise-orm>=0.20.0"')

    # Configuration
    if configuration == "pydantic_settings":
        dependencies.append('"pydantic-settings>=2.0.0"')
    elif configuration == "python_dotenv":
        dependencies.append('"python-dotenv>=1.0.0"')
    elif configuration == "dynaconf":
        dependencies.append('"dynaconf>=3.2.0"')

    # Logging
    if logging == "structlog":
        dependencies.append('"structlog>=23.0.0"')
    elif logging == "loguru":
        dependencies.append('"loguru>=0.7.0"')

    # HTTP Client
    if http_client == "httpx":
        dependencies.append('"httpx>=0.26.0"')
    elif http_client == "requests":
        dependencies.append('"requests>=2.31.0"')
    elif http_client == "aiohttp":
        dependencies.append('"aiohttp>=3.9.0"')

    # Build dev dependencies
    dev_deps = []

    if testing == "pytest":
        dev_deps.extend([
            '"pytest>=8.0.0"',
            '"pytest-cov>=4.1.0"',
            '"pytest-asyncio>=0.23.0"',
        ])
    elif testing == "unittest":
        dev_deps.append('"coverage>=7.0.0"')

    if linting == "ruff":
        dev_deps.append('"ruff>=0.2.0"')
    elif linting == "flake8_black":
        dev_deps.extend([
            '"flake8>=7.0.0"',
            '"black>=24.0.0"',
            '"isort>=5.13.0"',
        ])

    if type_checking == "mypy":
        dev_deps.append('"mypy>=1.8.0"')
    elif type_checking == "pyright":
        dev_deps.append('"pyright>=1.1.0"')

    dependencies_str = ",\n    ".join(dependencies) if dependencies else ""
    dev_deps_str = ",\n    ".join(dev_deps) if dev_deps else ""

    # Generate pyproject.toml
    content = f'''[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{service_name}"
version = "0.1.0"
description = "{description}"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    {dependencies_str}
]

[project.optional-dependencies]
dev = [
    {dev_deps_str}
]

[tool.hatch.build.targets.wheel]
packages = ["src/{service_name}"]

'''

    # Add pytest configuration if using pytest
    if testing == "pytest":
        content += '''[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = "-v --cov=src --cov-report=term-missing"

'''

    # Add ruff configuration if using ruff
    if linting == "ruff":
        content += '''[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "C4", "SIM"]

[tool.ruff.format]
quote-style = "double"

'''

    # Add mypy configuration if using mypy
    if type_checking == "mypy":
        content += '''[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

'''

    return content


def generate_pyproject_toml_poetry(
    service_name: str,
    python_standards: dict[str, Any],
    description: str = "Generated by Reflow"
) -> str:
    """Generate pyproject.toml for Poetry build system."""

    web_framework = python_standards.get("web_framework", {}).get("value", "fastapi")
    orm = python_standards.get("orm", {}).get("value", "sqlalchemy")
    testing = python_standards.get("testing_framework", {}).get("value", "pytest")
    linting = python_standards.get("linting", {}).get("value", "ruff")
    type_checking = python_standards.get("type_checking", {}).get("value", "mypy")

    content = f'''[tool.poetry]
name = "{service_name}"
version = "0.1.0"
description = "{description}"
authors = ["Generated by Reflow"]
readme = "README.md"
packages = [{{include = "{service_name}", from = "src"}}]

[tool.poetry.dependencies]
python = "^3.11"
'''

    # Add dependencies based on standards
    if web_framework == "fastapi":
        content += '''fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
'''

    if orm == "sqlalchemy":
        content += 'sqlalchemy = "^2.0.0"\n'

    content += '''
[tool.poetry.group.dev.dependencies]
'''

    if testing == "pytest":
        content += '''pytest = "^8.0.0"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.23.0"
'''

    if linting == "ruff":
        content += 'ruff = "^0.2.0"\n'

    if type_checking == "mypy":
        content += 'mypy = "^1.8.0"\n'

    content += '''
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
'''

    return content


def generate_pyproject_toml_uv(
    service_name: str,
    python_standards: dict[str, Any],
    description: str = "Generated by Reflow"
) -> str:
    """Generate pyproject.toml for uv build system."""
    # uv uses standard pyproject.toml format, similar to hatchling
    # but we'll add uv-specific configuration

    content = generate_pyproject_toml_hatchling(service_name, python_standards, description)

    # Add uv-specific section
    content += '''[tool.uv]
dev-dependencies = [
    # Dev dependencies managed by uv
]

'''

    return content


def generate_main_py(service_name: str, web_framework: str) -> str:
    """Generate main.py for the service."""

    if web_framework == "fastapi":
        return f'''"""
{service_name} - Main Application Entry Point

Generated by Reflow v3.20.0
"""

from fastapi import FastAPI
from contextlib import asynccontextmanager
import structlog

logger = structlog.get_logger()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan handler."""
    logger.info("{service_name}_startup", message="Starting {service_name}")
    yield
    logger.info("{service_name}_shutdown", message="Shutting down {service_name}")


app = FastAPI(
    title="{service_name}",
    description="Generated by Reflow",
    version="0.1.0",
    lifespan=lifespan,
)


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {{"status": "healthy", "service": "{service_name}"}}


@app.get("/")
async def root():
    """Root endpoint."""
    return {{"message": "Welcome to {service_name}"}}
'''

    elif web_framework == "flask":
        return f'''"""
{service_name} - Main Application Entry Point

Generated by Reflow v3.20.0
"""

from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/health")
def health_check():
    """Health check endpoint."""
    return jsonify({{"status": "healthy", "service": "{service_name}"}})


@app.route("/")
def root():
    """Root endpoint."""
    return jsonify({{"message": "Welcome to {service_name}"}})


if __name__ == "__main__":
    app.run(debug=True)
'''

    else:
        return f'''"""
{service_name} - Main Application Entry Point

Generated by Reflow v3.20.0
"""


def main():
    """Main entry point."""
    print("Hello from {service_name}")


if __name__ == "__main__":
    main()
'''


def generate_init_py(service_name: str) -> str:
    """Generate __init__.py for the package."""
    return f'''"""
{service_name} package

Generated by Reflow v3.20.0
"""

__version__ = "0.1.0"
'''


def generate_test_main_py(service_name: str, web_framework: str, testing: str) -> str:
    """Generate test file for main module."""

    if testing == "pytest" and web_framework == "fastapi":
        return f'''"""
Tests for {service_name} main module

Generated by Reflow v3.20.0
"""

import pytest
from fastapi.testclient import TestClient

from {service_name}.main import app


@pytest.fixture
def client():
    """Test client fixture."""
    return TestClient(app)


def test_health_check(client):
    """Test health check endpoint."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"


def test_root(client):
    """Test root endpoint."""
    response = client.get("/")
    assert response.status_code == 200
    assert "message" in response.json()
'''

    elif testing == "pytest":
        return f'''"""
Tests for {service_name} main module

Generated by Reflow v3.20.0
"""

import pytest

from {service_name}.main import main


def test_main():
    """Test main function."""
    # Add your tests here
    assert True
'''

    else:
        return f'''"""
Tests for {service_name} main module

Generated by Reflow v3.20.0
"""

import unittest


class TestMain(unittest.TestCase):
    """Test cases for main module."""

    def test_placeholder(self):
        """Placeholder test."""
        self.assertTrue(True)


if __name__ == "__main__":
    unittest.main()
'''


def generate_readme(service_name: str, python_standards: dict[str, Any]) -> str:
    """Generate README.md for the service."""

    dep_manager = python_standards.get("dependency_manager", {}).get("value", "hatchling")
    testing = python_standards.get("testing_framework", {}).get("value", "pytest")
    linting = python_standards.get("linting", {}).get("value", "ruff")

    # Install commands based on dependency manager
    if dep_manager == "hatchling":
        install_cmd = "pip install -e .[dev]"
        lock_cmd = "pip-compile pyproject.toml -o requirements.lock"
    elif dep_manager == "poetry":
        install_cmd = "poetry install"
        lock_cmd = "poetry lock"
    elif dep_manager == "uv":
        install_cmd = "uv pip install -e .[dev]"
        lock_cmd = "uv lock"
    else:
        install_cmd = "pip install -e .[dev]"
        lock_cmd = "pip freeze > requirements.txt"

    return f'''# {service_name}

Generated by Reflow v3.20.0

## Setup

```bash
# Install dependencies
{install_cmd}

# Generate lock file
{lock_cmd}
```

## Development

```bash
# Run tests
{testing if testing == "pytest" else "python -m unittest discover"}

# Run linter
{linting if linting == "ruff" else "flake8 src/ && black --check src/"}

# Type checking
mypy src/
```

## Running

```bash
# Development server
uvicorn {service_name}.main:app --reload

# Production
uvicorn {service_name}.main:app --host 0.0.0.0 --port 8000
```
'''


def generate_project_structure(
    system_root: str,
    service_name: str,
    standards: dict[str, Any],
    output_dir: Optional[str] = None,
    dry_run: bool = False,
    force: bool = False
) -> dict[str, str]:
    """
    Generate complete project structure.

    Returns dict of file_path -> content
    """
    python_standards = get_python_standards(standards)

    dep_manager = python_standards.get("dependency_manager", {}).get("value", "hatchling")
    web_framework = python_standards.get("web_framework", {}).get("value", "fastapi")
    testing = python_standards.get("testing_framework", {}).get("value", "pytest")
    linting = python_standards.get("linting", {}).get("value", "ruff")

    # Determine output directory
    if output_dir:
        base_dir = Path(output_dir)
    else:
        base_dir = Path(system_root) / "services" / service_name

    files = {}

    # Generate pyproject.toml based on dependency manager
    if dep_manager == "poetry":
        pyproject = generate_pyproject_toml_poetry(service_name, python_standards)
    elif dep_manager == "uv":
        pyproject = generate_pyproject_toml_uv(service_name, python_standards)
    else:  # hatchling or others
        pyproject = generate_pyproject_toml_hatchling(service_name, python_standards)

    files[str(base_dir / "pyproject.toml")] = pyproject

    # Generate source files
    src_dir = base_dir / "src" / service_name
    files[str(src_dir / "__init__.py")] = generate_init_py(service_name)
    files[str(src_dir / "main.py")] = generate_main_py(service_name, web_framework)

    # Generate test files
    tests_dir = base_dir / "tests"
    files[str(tests_dir / "__init__.py")] = '"""Test package."""\n'
    files[str(tests_dir / "test_main.py")] = generate_test_main_py(service_name, web_framework, testing)

    # Generate README
    files[str(base_dir / "README.md")] = generate_readme(service_name, python_standards)

    # Generate ruff config if using ruff
    if linting == "ruff":
        files[str(base_dir / ".ruff.toml")] = '''# Ruff configuration (also in pyproject.toml)
# This file can be used for editor integration

line-length = 88
target-version = "py311"

[lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "C4", "SIM"]
'''

    # Generate py.typed marker for type checking
    files[str(src_dir / "py.typed")] = ''

    return files


def write_files(files: dict[str, str], force: bool = False) -> list[str]:
    """Write files to disk."""
    written = []

    for path, content in files.items():
        file_path = Path(path)

        # Check if file exists
        if file_path.exists() and not force:
            print(f"SKIP: {path} (exists, use --force to overwrite)")
            continue

        # Create parent directories
        file_path.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        with open(file_path, "w") as f:
            f.write(content)

        written.append(path)
        print(f"CREATE: {path}")

    return written


def main():
    parser = argparse.ArgumentParser(
        description="Generate Python project structure based on development standards",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    parser.add_argument("system_root", help="Path to system root directory")
    parser.add_argument("--service", "-s", required=True, help="Service/project name")
    parser.add_argument("--standards", help="Path to development_standards.json")
    parser.add_argument("--output-dir", "-o", help="Output directory")
    parser.add_argument("--dry-run", "-n", action="store_true", help="Show what would be generated")
    parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing files")
    parser.add_argument("--description", "-d", default="Generated by Reflow", help="Project description")

    args = parser.parse_args()

    # Load standards
    if args.standards:
        with open(args.standards) as f:
            standards = json.load(f)
    else:
        standards = load_development_standards(args.system_root)
        if not standards:
            print("WARNING: No development_standards.json found, using defaults")
            # Create minimal standards with defaults
            standards = {
                "language_standards": {
                    "python": {
                        "interface_strategy": {"value": "protocol_di"},
                        "dependency_manager": {"value": "hatchling"},
                        "lock_file_generation": {"value": True},
                        "web_framework": {"value": "fastapi"},
                        "orm": {"value": "sqlalchemy"},
                        "testing_framework": {"value": "pytest"},
                        "linting": {"value": "ruff"},
                        "type_checking": {"value": "mypy"},
                        "logging": {"value": "structlog"},
                        "http_client": {"value": "httpx"},
                        "configuration": {"value": "pydantic_settings"}
                    }
                }
            }

    # Generate project structure
    files = generate_project_structure(
        system_root=args.system_root,
        service_name=args.service,
        standards=standards,
        output_dir=args.output_dir,
        dry_run=args.dry_run,
        force=args.force
    )

    if args.dry_run:
        print("\nDRY RUN - Files that would be generated:\n")
        for path in files:
            print(f"  {path}")
        print(f"\nTotal: {len(files)} files")
        return 0

    # Write files
    written = write_files(files, force=args.force)

    print(f"\nSUCCESS: Generated {len(written)} files for {args.service}")

    # Print next steps
    python_standards = get_python_standards(standards)
    dep_manager = python_standards.get("dependency_manager", {}).get("value", "hatchling")

    print("\nNext steps:")
    if dep_manager == "poetry":
        print("  cd services/" + args.service)
        print("  poetry install")
    elif dep_manager == "uv":
        print("  cd services/" + args.service)
        print("  uv pip install -e .[dev]")
    else:
        print("  cd services/" + args.service)
        print("  pip install -e .[dev]")

    return 0


if __name__ == "__main__":
    sys.exit(main())
