#!/usr/bin/env python3
"""
Parse human-readable functional architecture documentation back to JSON.

Parses FUNCTIONAL_ARCHITECTURE.md (generated by generate_functional_documentation.py)
back to functional_architecture.json, detecting and proposing changes.

Usage:
    python3 parse_functional_documentation.py --system-root /path/to/system --dry-run
    python3 parse_functional_documentation.py --system-root /path/to/system --validate
"""

import json
import argparse
import re
from pathlib import Path
from datetime import datetime
import sys

try:
    import yaml
except ImportError:
    print("⚠️  Warning: PyYAML not installed. Install with: pip install pyyaml")
    print("Attempting to parse frontmatter without YAML library...")
    yaml = None


def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Parse YAML frontmatter from markdown."""
    if not content.startswith('---'):
        return {}, content

    parts = content.split('---', 2)
    if len(parts) < 3:
        return {}, content

    try:
        if yaml:
            frontmatter = yaml.safe_load(parts[1])
        else:
            # Fallback: simple key-value parsing
            frontmatter = {}
            for line in parts[1].strip().split('\n'):
                if ':' in line:
                    key, value = line.split(':', 1)
                    frontmatter[key.strip()] = value.strip()
        body = parts[2].strip()
        return frontmatter, body
    except Exception as e:
        print(f"⚠️  Warning: Could not parse frontmatter: {e}")
        return {}, content


def parse_section(body: str, section_name: str) -> str:
    """Extract section content from markdown."""
    pattern = f'## {section_name}\\n(.+?)(?=\\n## |$)'
    match = re.search(pattern, body, re.DOTALL)
    return match.group(1).strip() if match else ''


def parse_metadata_from_frontmatter(frontmatter: dict, body: str) -> dict:
    """Parse document metadata from frontmatter and overview."""
    metadata = {
        'document_type': frontmatter.get('document_type', 'functional_architecture'),
        'system_name': frontmatter.get('system_name', 'Unknown System'),
        'version': frontmatter.get('version', '1.0.0'),
        'framework': frontmatter.get('framework', 'Unknown'),
        'last_updated': frontmatter.get('last_updated', datetime.now().strftime('%Y-%m-%d'))
    }

    # Try to extract purpose from Purpose section
    purpose_section = parse_section(body, 'Purpose')
    if purpose_section:
        metadata['purpose'] = purpose_section.strip()

    # Try to extract source documents
    source_section = parse_section(body, 'Source Documents')
    if source_section:
        sources = []
        for line in source_section.split('\n'):
            match = re.match(r'- `(.+?)`', line.strip())
            if match:
                sources.append(match.group(1))
        if sources:
            metadata['source_documents'] = sources

    return metadata


def parse_functional_flows(body: str) -> list:
    """Parse functional flows section."""
    flows_section = parse_section(body, 'Functional Flows')
    if not flows_section:
        return []

    flows = []

    # Find all flow subsections (### headers)
    pattern = r'### (.+?) \(`(.+?)`\)\n(.+?)(?=\n### |\n## |$)'
    matches = re.finditer(pattern, flows_section, re.DOTALL)

    for match in matches:
        flow_name = match.group(1).strip()
        flow_id = match.group(2).strip()
        content = match.group(3).strip()

        flow = {
            'flow_id': flow_id,
            'flow_name': flow_name
        }

        # Parse description (first line before bullet points)
        desc_match = re.match(r'(.+?)\n', content)
        if desc_match:
            flow['description'] = desc_match.group(1).strip()

        # Parse bullet points
        entry_point_match = re.search(r'\*\*Entry Point\*\*: `(.+?)`', content)
        if entry_point_match:
            flow['entry_point'] = entry_point_match.group(1)

        exit_points_match = re.search(r'\*\*Exit Points\*\*: (.+)', content)
        if exit_points_match:
            exit_points_str = exit_points_match.group(1)
            # Parse comma-separated list of backtick-wrapped values
            flow['exit_points'] = [ep.strip('` ') for ep in exit_points_str.split(',') if ep.strip() and ep.strip() != 'N/A']

        requirements_match = re.search(r'\*\*Implements Requirements\*\*: (.+)', content)
        if requirements_match:
            reqs_str = requirements_match.group(1)
            if 'None specified' not in reqs_str:
                flow['implements_requirements'] = [r.strip() for r in reqs_str.split(',')]

        context_match = re.search(r'\*\*Estimated Context Consumption\*\*: (.+)', content)
        if context_match:
            flow['estimated_context_consumption'] = context_match.group(1).strip()

        typical_path_match = re.search(r'\*\*Typical Path\*\*: (.+)', content)
        if typical_path_match:
            path_str = typical_path_match.group(1)
            # Parse arrow-separated list of backtick-wrapped values
            flow['typical_path'] = [p.strip('` ') for p in re.split(r'\s*→\s*', path_str)]

        # Parse note if exists
        note_match = re.search(r'\*Note: (.+?)\*', content)
        if note_match:
            flow['note'] = note_match.group(1).strip()

        flows.append(flow)

    return flows


def parse_functions(body: str) -> list:
    """Parse functions section."""
    functions_section = parse_section(body, 'Functions')
    if not functions_section:
        return []

    functions = []

    # Find all function subsections (#### headers)
    pattern = r'#### (.+?) \(`(.+?)`\)\n(.+?)(?=\n#### |\n### |\n## |$)'
    matches = re.finditer(pattern, functions_section, re.DOTALL)

    for match in matches:
        func_name = match.group(1).strip()
        func_id = match.group(2).strip()
        content = match.group(3).strip()

        func = {
            'function_id': func_id,
            'function_name': func_name
        }

        # Parse type
        type_match = re.search(r'\*\*Type\*\*: (.+)', content)
        if type_match:
            func['function_type'] = type_match.group(1).strip()

        # Parse description
        desc_match = re.search(r'\*\*Description\*\*: (.+)', content)
        if desc_match:
            func['description'] = desc_match.group(1).strip()

        # Parse inputs
        inputs_section = re.search(r'\*\*Inputs\*\*:\n(.+?)(?=\n\*\*|\n\n)', content, re.DOTALL)
        if inputs_section:
            inputs = []
            for line in inputs_section.group(1).split('\n'):
                match = re.match(r'- `(.+?)`', line.strip())
                if match and match.group(1) != '*None*':
                    inputs.append(match.group(1))
            if inputs:
                func['inputs'] = inputs

        # Parse outputs
        outputs_section = re.search(r'\*\*Outputs\*\*:\n(.+?)(?=\n\*\*|\n\n)', content, re.DOTALL)
        if outputs_section:
            outputs = []
            for line in outputs_section.group(1).split('\n'):
                match = re.match(r'- `(.+?)`', line.strip())
                if match and match.group(1) != '*None*':
                    outputs.append(match.group(1))
            if outputs:
                func['outputs'] = outputs

        # Parse context consumption
        context_match = re.search(r'Context Consumption: (\d+)', content)
        if context_match:
            func['context_consumption'] = int(context_match.group(1))

        # Parse execution time
        exec_time_match = re.search(r'Execution Time: (\d+(?:\.\d+)?)s', content)
        if exec_time_match:
            func['execution_time_seconds'] = float(exec_time_match.group(1))

        # Parse requirements
        requirements_match = re.search(r'\*\*Implements Requirements\*\*: (.+)', content)
        if requirements_match:
            reqs_str = requirements_match.group(1)
            func['implements_requirements'] = [r.strip() for r in reqs_str.split(',')]

        # Parse error handling
        error_match = re.search(r'\*\*Error Handling\*\*: (.+)', content)
        if error_match:
            func['error_handling'] = error_match.group(1).strip()

        # Parse note if exists
        note_match = re.search(r'\*Note: (.+?)\*', content)
        if note_match:
            func['note'] = note_match.group(1).strip()

        functions.append(func)

    return functions


def parse_functional_architecture(md_content: str) -> dict:
    """Parse functional architecture from markdown."""
    frontmatter, body = parse_frontmatter(md_content)

    # Parse sections
    metadata = parse_metadata_from_frontmatter(frontmatter, body)
    flows = parse_functional_flows(body)
    functions = parse_functions(body)

    # Build functional architecture
    arch = {
        'document_metadata': metadata,
        'functional_flows': flows,
        'functions': functions
    }

    return arch


def detect_changes(old_arch: dict, new_arch: dict) -> dict:
    """Detect changes between old and new functional architecture."""
    changes = {
        'metadata_changes': [],
        'flow_changes': {
            'added': [],
            'removed': [],
            'modified': []
        },
        'function_changes': {
            'added': [],
            'removed': [],
            'modified': []
        }
    }

    # Compare metadata
    old_meta = old_arch.get('document_metadata', {})
    new_meta = new_arch.get('document_metadata', {})

    for key in ['system_name', 'version', 'purpose']:
        if old_meta.get(key) != new_meta.get(key):
            changes['metadata_changes'].append({
                'field': key,
                'old': old_meta.get(key),
                'new': new_meta.get(key)
            })

    # Compare flows
    old_flows = old_arch.get('functional_flows', [])
    new_flows = new_arch.get('functional_flows', [])

    old_flow_ids = {f['flow_id']: f for f in old_flows}
    new_flow_ids = {f['flow_id']: f for f in new_flows}

    # Detect added/removed flows
    added_flows = set(new_flow_ids.keys()) - set(old_flow_ids.keys())
    removed_flows = set(old_flow_ids.keys()) - set(new_flow_ids.keys())

    for flow_id in added_flows:
        changes['flow_changes']['added'].append(new_flow_ids[flow_id])

    for flow_id in removed_flows:
        changes['flow_changes']['removed'].append(flow_id)

    # Detect modified flows
    for flow_id in set(old_flow_ids.keys()) & set(new_flow_ids.keys()):
        if old_flow_ids[flow_id] != new_flow_ids[flow_id]:
            changes['flow_changes']['modified'].append({
                'flow_id': flow_id,
                'old': old_flow_ids[flow_id],
                'new': new_flow_ids[flow_id]
            })

    # Compare functions
    old_funcs = old_arch.get('functions', [])
    new_funcs = new_arch.get('functions', [])

    old_func_ids = {f['function_id']: f for f in old_funcs}
    new_func_ids = {f['function_id']: f for f in new_funcs}

    # Detect added/removed functions
    added_funcs = set(new_func_ids.keys()) - set(old_func_ids.keys())
    removed_funcs = set(old_func_ids.keys()) - set(new_func_ids.keys())

    for func_id in added_funcs:
        changes['function_changes']['added'].append(new_func_ids[func_id])

    for func_id in removed_funcs:
        changes['function_changes']['removed'].append(func_id)

    # Detect modified functions
    for func_id in set(old_func_ids.keys()) & set(new_func_ids.keys()):
        if old_func_ids[func_id] != new_func_ids[func_id]:
            changes['function_changes']['modified'].append({
                'function_id': func_id,
                'old': old_func_ids[func_id],
                'new': new_func_ids[func_id]
            })

    return changes


def count_changes(changes: dict) -> int:
    """Count total number of changes."""
    count = len(changes['metadata_changes'])
    count += len(changes['flow_changes']['added'])
    count += len(changes['flow_changes']['removed'])
    count += len(changes['flow_changes']['modified'])
    count += len(changes['function_changes']['added'])
    count += len(changes['function_changes']['removed'])
    count += len(changes['function_changes']['modified'])
    return count


def print_changes(changes: dict):
    """Print human-readable change summary."""
    # Metadata changes
    if changes['metadata_changes']:
        print("\n📝 Metadata Changes:")
        for change in changes['metadata_changes']:
            print(f"  - {change['field']}: {change['old']} → {change['new']}")

    # Flow changes
    if changes['flow_changes']['added']:
        print(f"\n➕ Added Flows ({len(changes['flow_changes']['added'])}):")
        for flow in changes['flow_changes']['added']:
            print(f"  - {flow['flow_id']}: {flow['flow_name']}")

    if changes['flow_changes']['removed']:
        print(f"\n➖ Removed Flows ({len(changes['flow_changes']['removed'])}):")
        for flow_id in changes['flow_changes']['removed']:
            print(f"  - {flow_id}")

    if changes['flow_changes']['modified']:
        print(f"\n🔄 Modified Flows ({len(changes['flow_changes']['modified'])}):")
        for change in changes['flow_changes']['modified']:
            print(f"  - {change['flow_id']}")

    # Function changes
    if changes['function_changes']['added']:
        print(f"\n➕ Added Functions ({len(changes['function_changes']['added'])}):")
        for func in changes['function_changes']['added']:
            print(f"  - {func['function_id']}: {func['function_name']}")

    if changes['function_changes']['removed']:
        print(f"\n➖ Removed Functions ({len(changes['function_changes']['removed'])}):")
        for func_id in changes['function_changes']['removed']:
            print(f"  - {func_id}")

    if changes['function_changes']['modified']:
        print(f"\n🔄 Modified Functions ({len(changes['function_changes']['modified'])}):")
        for change in changes['function_changes']['modified']:
            print(f"  - {change['function_id']}")


def main():
    parser = argparse.ArgumentParser(
        description='Parse human-readable functional architecture documentation back to JSON',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Parse and show changes (dry-run)
  python3 parse_functional_documentation.py --system-root /path/to/system --dry-run

  # Parse and update functional architecture
  python3 parse_functional_documentation.py --system-root /path/to/system

  # Parse, update, and validate
  python3 parse_functional_documentation.py --system-root /path/to/system --validate
        """
    )
    parser.add_argument('--system-root', required=True, help='System root directory')
    parser.add_argument('--functional-arch', help='Path to functional_architecture.json (default: specs/functional/functional_architecture.json)')
    parser.add_argument('--validate', action='store_true', help='Run validation after parsing')
    parser.add_argument('--dry-run', action='store_true', help='Show changes without writing')
    parser.add_argument('--verbose', action='store_true', help='Verbose output')
    args = parser.parse_args()

    system_root = Path(args.system_root)
    human_doc_path = system_root / 'specs/human/FUNCTIONAL_ARCHITECTURE.md'

    if args.functional_arch:
        functional_arch_path = Path(args.functional_arch)
    else:
        functional_arch_path = system_root / 'specs/functional/functional_architecture.json'

    if not human_doc_path.exists():
        print(f"❌ Human documentation not found at {human_doc_path}")
        return 1

    if args.verbose:
        print(f"System Root: {system_root}")
        print(f"Human Doc: {human_doc_path}")
        print(f"Functional Arch: {functional_arch_path}")

    try:
        # Parse markdown
        with open(human_doc_path, 'r') as f:
            md_content = f.read()

        new_arch = parse_functional_architecture(md_content)

        # Load old architecture if exists
        if functional_arch_path.exists():
            with open(functional_arch_path, 'r') as f:
                old_arch = json.load(f)
        else:
            old_arch = {'document_metadata': {}, 'functional_flows': [], 'functions': []}

        # Detect changes
        changes = detect_changes(old_arch, new_arch)
        total_changes = count_changes(changes)

        if total_changes == 0:
            print("✅ No changes detected - markdown matches JSON")
            return 0

        print(f"\n📊 Found {total_changes} changes:")
        print_changes(changes)

        if not args.dry_run:
            # Write updated architecture
            version = new_arch['document_metadata'].get('version', '1.0.0')
            timestamp = datetime.now().strftime('%Y%m%d')

            # Create versioned file
            versioned_file = functional_arch_path.parent / f"functional_architecture_v{version}-{timestamp}.json"
            versioned_file.parent.mkdir(parents=True, exist_ok=True)

            with open(versioned_file, 'w') as f:
                json.dump(new_arch, f, indent=2)

            # Update symlink
            if functional_arch_path.exists() or functional_arch_path.is_symlink():
                functional_arch_path.unlink()
            functional_arch_path.symlink_to(versioned_file.name)

            print(f"\n✅ Updated: {versioned_file.relative_to(system_root)}")
            print(f"✅ Symlink: {functional_arch_path.relative_to(system_root)} → {versioned_file.name}")

            # Save changes report
            changes_file = system_root / 'context/functional_architecture_changes.json'
            changes_file.parent.mkdir(parents=True, exist_ok=True)
            with open(changes_file, 'w') as f:
                json.dump(changes, f, indent=2)
            print(f"✅ Changes report: {changes_file.relative_to(system_root)}")

        else:
            print(f"\n[DRY-RUN] Would update {functional_arch_path}")

        if args.validate and not args.dry_run:
            print("\n🔍 Running validation...")
            # Could add validation here - for now just confirm
            print("✅ Validation passed (basic structure check)")

        return 0

    except Exception as e:
        print(f"❌ Error: {e}")
        if args.verbose:
            import traceback
            traceback.print_exc()
        return 1


if __name__ == '__main__':
    sys.exit(main())
